[package]
name = "btsnoop"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
byteorder = "1.5"
bytes = "1.7"
pdl-runtime = "0.3"
num_enum = "0.7"
